[package]
name = "more_ranges"
version = "0.2.0"
authors = ["Anders Evensen"]
edition = "2021"
rust-version = "1.83.0"
description = "Range types not provided in the standard library."
readme = "README.md"
repository = "https://github.com/Anders429/more_ranges"
license = "MIT OR Apache-2.0"
keywords = ["range", "exclusive", "excluded", "bound", "rangebound"]
categories = ["data-structures", "no-std"]
exclude = [".github/*"]

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[dependencies]
serde_core = {version = "1.0.228", default-features = false, optional = true}

[dev-dependencies]
claims = "0.8.0"
serde_assert = "0.8.0"

[features]
alloc = []
serde = ["serde_core"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(doc_cfg)"]}
